app:
  allowed-origins: http://localhost:5173
server:
  port: 8081
  servlet:
    context-path: /drawio
spring:
  autoconfigure:
    # 手动创建 OpenAiApi，不走 Spring AI 自动装配，因为要使用用户的key
    exclude:
      - org.springframework.ai.autoconfigure.openai.OpenAiAutoConfiguration
      - org.springframework.ai.autoconfigure.chat.client.ChatClientAutoConfiguration
  application:
    name: easy-draw-backend
  profiles:
    include: local

